version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: mydatabase
      # MYSQL_USER: myuser    
      # MYSQL_PASSWORD: mypassword  
    ports:
      - "3306:3306"
    volumes:    
      - /Users/prashant/Documents/MySQL Volumes/vol1:/var/lib/mysql # will be managed my me locally

volumes:
  mysql_data: #Since you're managing the storage yourself, you don’t need Docker to create a named volume.

  #  docker logs mysql_container