version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prashant
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    volumes:
      - "/Users/prashant/Documents/Postgress Volumes/data1:/var/lib/postgresql/data"
