version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:    
      - mysql_data:/var/lib/mysql  # will be mangerd by docker volumes 

volumes:
  mysql_data: